name: cliente_tutiendita
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  animate_do: ^3.3.4
  badges: ^3.1.2
  cloud_firestore: ^5.0.0
  country_code_picker: ^3.0.0
  curved_navigation_bar: ^1.0.6
  equatable: ^2.0.5
  firebase_auth: ^5.1.2
  firebase_core: ^3.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_spinkit: ^5.2.1
  font_awesome_flutter: ^10.7.0
  formz: ^0.7.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.3
  step_progress_indicator: ^1.0.2
  url_launcher: ^6.1.11
  whatsapp_unilink: ^2.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/tutiendida.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#080808"
  android_12:
    color: "#080808"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
